"use client";
import { useState } from "react";
import { api } from "@/lib/api";
import { useStore } from "@/lib/store";
import { buildContext } from "@/lib/analytics";
import Badge from "./Badge";
import JsonView from "./JsonView";
export type Field = { name: string; label: string; type?: "text" | "textarea" | "select" | "image"; options?: string[]; placeholder?: string };
export default function AIPage({ title, desc, module, fields, note, action, cta = "Generate" }: { title: string; desc: string; module: string; fields: Field[]; note?: string; action?: { type: string; text: string; cost?: number; target?: string }; cta?: string }) {
  const { d, queueAction } = useStore();
  const [v, setV] = useState<any>({}); const [img, setImg] = useState<any>(null); const [res, setRes] = useState<any>(null); const [err, setErr] = useState(""); const [busy, setBusy] = useState(false); const [queued, setQueued] = useState(false);
  const onFile = (f?: File) => { if (!f) return setImg(null); const r = new FileReader(); r.onload = () => { const s = String(r.result); setImg({ media_type: f.type, data: s.split(",")[1] }); }; r.readAsDataURL(f); };
  async function run() {
    setBusy(true); setErr(""); setRes(null); setQueued(false);
    try { const r = await api("/api/ai/run", { method: "POST", body: JSON.stringify({ module, input: v, context: buildContext(d), image: img }) }); setRes(r.result); }
    catch (e: any) { setErr(e.message); } finally { setBusy(false); }
  }
  const cls = "w-full rounded-lg border border-line bg-ink px-3 py-2 text-sm";
  return (
    <div className="space-y-6">
      <div><h1 className="text-2xl font-bold">{title}</h1><p className="text-sm text-neutral-400">{desc}</p></div>
      {note && <p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-200">{note}</p>}
      <div className="grid gap-4 rounded-xl border border-line bg-panel p-5 md:grid-cols-2">
        {fields.map((f) => (<label key={f.name} className={`text-xs text-neutral-400 ${f.type === "textarea" ? "md:col-span-2" : ""}`}>{f.label}
          {f.type === "textarea" ? <textarea rows={3} className={cls + " mt-1"} placeholder={f.placeholder} onChange={(e) => setV({ ...v, [f.name]: e.target.value })} />
            : f.type === "select" ? <select className={cls + " mt-1"} onChange={(e) => setV({ ...v, [f.name]: e.target.value })}><option value="">Select…</option>{f.options!.map((o) => <option key={o}>{o}</option>)}</select>
            : f.type === "image" ? <input type="file" accept="image/png,image/jpeg,image/webp" className={cls + " mt-1"} onChange={(e) => onFile(e.target.files?.[0])} />
            : <input className={cls + " mt-1"} placeholder={f.placeholder} onChange={(e) => setV({ ...v, [f.name]: e.target.value })} />}</label>))}
        <div className="md:col-span-2 flex items-center gap-3"><button onClick={run} disabled={busy} className="rounded-lg bg-accent px-5 py-2 text-sm font-semibold text-ink disabled:opacity-50">{busy ? "Thinking…" : cta}</button>
          <span className="text-[11px] text-neutral-500">Uses your {Object.values(d.src).filter((s) => s !== "none").length ? "uploaded/demo analytics" : "no analytics (none loaded)"} as context.</span></div>
      </div>
      {err && <p className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{err}</p>}
      {res && (<div className="space-y-3"><div className="flex items-center gap-3"><Badge kind="ai" /><span className="text-xs text-neutral-500">Generated by Claude. Verify before acting; this is not a guaranteed prediction.</span>
        {action && <button disabled={queued} onClick={() => { queueAction({ action: action.type, what_will_happen: action.text, cost: action.cost ?? 0, target: action.target ?? "—", schedule: "Not scheduled", content: res }); setQueued(true); }} className="ml-auto rounded-lg border border-accent px-3 py-1.5 text-xs text-accent disabled:opacity-50">{queued ? "Queued — see Settings → Approvals" : "Send to approval queue"}</button>}</div>
        <JsonView v={res} /></div>)}
    </div>
  );
}
