"""initial schema"""
revision = '0001'
down_revision = None
import sqlalchemy as sa
from alembic import op

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('performance', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_source'), 'hashtags', ['source'], unique=False)
    op.create_index(op.f('ix_hashtags_tag'), 'hashtags', ['tag'], unique=False)
    op.create_table('trends',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trends_observed_at'), 'trends', ['observed_at'], unique=False)
    op.create_index(op.f('ix_trends_source'), 'trends', ['source'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('brands',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_user_id'), 'brands', ['user_id'], unique=False)
    op.create_table('ad_campaigns',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_brand_id'), 'ad_campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_source'), 'ad_campaigns', ['source'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=40), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('inputs_ref', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_brand_id'), 'ai_recommendations', ['brand_id'], unique=False)
    op.create_table('competitors',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_brand_id'), 'competitors', ['brand_id'], unique=False)
    op.create_index(op.f('ix_competitors_source'), 'competitors', ['source'], unique=False)
    op.create_table('content_ideas',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_ideas_brand_id'), 'content_ideas', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_source'), 'content_ideas', ['source'], unique=False)
    op.create_table('instagram_accounts',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('ig_user_id', sa.String(length=64), nullable=True),
    sa.Column('token_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_brand_id'), 'instagram_accounts', ['brand_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_source'), 'instagram_accounts', ['source'], unique=False)
    op.create_table('marketing_reports',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_reports_brand_id'), 'marketing_reports', ['brand_id'], unique=False)
    op.create_table('pending_actions',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('what_will_happen', sa.Text(), nullable=False),
    sa.Column('cost_inr', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_brand_id'), 'pending_actions', ['brand_id'], unique=False)
    op.create_table('products',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price_inr', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_table('ad_creatives',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('hook_type', sa.String(length=30), nullable=True),
    sa.Column('copy', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_creatives_campaign_id'), 'ad_creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_creatives_source'), 'ad_creatives', ['source'], unique=False)
    op.create_table('ad_performance',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_performance_campaign_id'), 'ad_performance', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_performance_day'), 'ad_performance', ['day'], unique=False)
    op.create_index(op.f('ix_ad_performance_source'), 'ad_performance', ['source'], unique=False)
    op.create_table('analytics',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('profile_visits', sa.Integer(), nullable=True),
    sa.Column('website_clicks', sa.Integer(), nullable=True),
    sa.Column('dms', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_account_id'), 'analytics', ['account_id'], unique=False)
    op.create_index(op.f('ix_analytics_day'), 'analytics', ['day'], unique=False)
    op.create_index(op.f('ix_analytics_source'), 'analytics', ['source'], unique=False)
    op.create_table('content_calendar',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('objective', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_calendar_brand_id'), 'content_calendar', ['brand_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_scheduled_for'), 'content_calendar', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_content_calendar_source'), 'content_calendar', ['source'], unique=False)
    op.create_table('instagram_posts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ig_media_id', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hook', sa.String(length=300), nullable=True),
    sa.Column('cta', sa.String(length=200), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_account_id'), 'instagram_posts', ['account_id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_ig_media_id'), 'instagram_posts', ['ig_media_id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_posted_at'), 'instagram_posts', ['posted_at'], unique=False)
    op.create_index(op.f('ix_instagram_posts_source'), 'instagram_posts', ['source'], unique=False)
    op.create_table('instagram_reels',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ig_media_id', sa.String(length=64), nullable=True),
    sa.Column('hook', sa.String(length=300), nullable=True),
    sa.Column('audio', sa.String(length=200), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_reels_account_id'), 'instagram_reels', ['account_id'], unique=False)
    op.create_index(op.f('ix_instagram_reels_ig_media_id'), 'instagram_reels', ['ig_media_id'], unique=False)
    op.create_index(op.f('ix_instagram_reels_posted_at'), 'instagram_reels', ['posted_at'], unique=False)
    op.create_index(op.f('ix_instagram_reels_source'), 'instagram_reels', ['source'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instagram_reels_source'), table_name='instagram_reels')
    op.drop_index(op.f('ix_instagram_reels_posted_at'), table_name='instagram_reels')
    op.drop_index(op.f('ix_instagram_reels_ig_media_id'), table_name='instagram_reels')
    op.drop_index(op.f('ix_instagram_reels_account_id'), table_name='instagram_reels')
    op.drop_table('instagram_reels')
    op.drop_index(op.f('ix_instagram_posts_source'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_posted_at'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_ig_media_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_account_id'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    op.drop_index(op.f('ix_content_calendar_source'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_scheduled_for'), table_name='content_calendar')
    op.drop_index(op.f('ix_content_calendar_brand_id'), table_name='content_calendar')
    op.drop_table('content_calendar')
    op.drop_index(op.f('ix_analytics_source'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_day'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_account_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_ad_performance_source'), table_name='ad_performance')
    op.drop_index(op.f('ix_ad_performance_day'), table_name='ad_performance')
    op.drop_index(op.f('ix_ad_performance_campaign_id'), table_name='ad_performance')
    op.drop_table('ad_performance')
    op.drop_index(op.f('ix_ad_creatives_source'), table_name='ad_creatives')
    op.drop_index(op.f('ix_ad_creatives_campaign_id'), table_name='ad_creatives')
    op.drop_table('ad_creatives')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pending_actions_brand_id'), table_name='pending_actions')
    op.drop_table('pending_actions')
    op.drop_index(op.f('ix_marketing_reports_brand_id'), table_name='marketing_reports')
    op.drop_table('marketing_reports')
    op.drop_index(op.f('ix_instagram_accounts_source'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_brand_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_content_ideas_source'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_brand_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_competitors_source'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_brand_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_ai_recommendations_brand_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_ad_campaigns_source'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_brand_id'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    op.drop_index(op.f('ix_brands_user_id'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trends_source'), table_name='trends')
    op.drop_index(op.f('ix_trends_observed_at'), table_name='trends')
    op.drop_table('trends')
    op.drop_index(op.f('ix_hashtags_tag'), table_name='hashtags')
    op.drop_index(op.f('ix_hashtags_source'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
